export enum OrderStatus {
    AWAITING_PAYMENT = 'AWAITING_PAYMENT',
    AWAITING_FUNDS = 'AWAITING_FUNDS',
    AWAITING_CONFIRMATION = 'AWAITING_CONFIRMATION',
    EXCHANGING = 'EXCHANGING',
    COMPLETED = 'COMPLETED'
}