import type {Metadata, Viewport} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import React from "react";
import Header from "@/app/layout/Header";
import CoinsProvider from "@/providers/CoinsProvider";
import {getCoins} from "@/services/getCoinsApi";
import Footer from "@/app/layout/Footer";
import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'

config.autoAddCss = false;
const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};
export const viewport: Viewport = {
    width: "device-width",
    initialScale: 1,
};

export default async function RootLayout({
                                             children,
                                         }: Readonly<{
    children: React.ReactNode;
}>) {

    const coins = await getCoins();
    return (
        <html lang="en">

        <body
            className={`${geistSans.variable} ${geistMono.variable} bg-[var(--bg-color)]`}>
        <div
            className="flex m-auto max-w-full flex-col min-h-screen items-center bg-zinc-50 font-sans dark:bg-black">
            <Header/>
            <main
                className="flex flex-1 flex-col dark:bg-black m-auto">
                <CoinsProvider coins={coins}>{children}</CoinsProvider>
            </main>
            <Footer/>

        </div>
        </body>

        </html>

    );
}
